Do not show logfile on ExtStorage's attach error
During attach the logfile is `None'. If the attach script
fails and we try to Tailfile() its logfile, TailFile
breaks with:

TypeError: coercing to Unicode: need string or buffer, NoneType found

Thus, we don't show the logfile, if ExtStorage's attach script fails.
Just throw the appropriate error.

Signed-off-by: Constantinos Venetsanopoulos <cven@grnet.gr>